# Generated by Django 6.0.3 on 2026-03-06 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("helpcard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_problems",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Назначена исполнителю",
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="helpcard.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_problems",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создана пользователем",
            ),
        ),
    ]
