# Generated by Django 6.0.3 on 2026-03-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helpcard", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="location_name",
            field=models.CharField(
                blank=True,
                help_text="Например: Мокшан, Пенза, Рамзай",
                max_length=100,
                verbose_name="Населенный пункт",
            ),
        ),
    ]
