# Generated by Django 5.2.6 on 2026-03-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helpcard", "0003_problem_location_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="executor_comment",
            field=models.TextField(blank=True, verbose_name="Комментарий исполнителя"),
        ),
    ]
